[package]
name = "vecta"
version = "0.1.0"
edition = "2021"
description = "A production-grade vector database built from scratch in Rust, benchmarked against FAISS"

[lib]
name = "vecta"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"] }
rand = "0.8"
memmap2 = "0.9"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tower = "0.5"
utoipa = { version = "4.2", features = ["axum_extras"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
toml = "0.8"

[[bin]]
name = "vecta-server"
path = "src/bin/vecta_server.rs"

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }

[build-dependencies]
pyo3-build-config = "0.29"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
